(#69) Remove React App Fetching from Trial Requests
NCIOCPL/clinical-trials-listing-app pull request #133
Opened 2021-08-17 14:22 UTC by alerosad

* implemented axios api request
* updated Disease component to use newly made axios client
* created axios support, similar to how useListingSupport works

2021-08-30 19:23 UTC, alinai commented
Verified  the request and response for DLPs and MLPs and  no trial found pages on React. Looks good to me. Thanks @seyilonge-nci!!

2021-09-01 13:57 UTC, alinai commented
Verified the request and response for DLPs and MLPs and no trial found pages on React. Looks good to me. Thanks @alerosad

2021-09-01 18:58 UTC, bryanpizzillo commented on src/services/api/clinical-trials-search-api/__tests__/getClinicalTrials.test.js
> +
This needs to disable net connects before all

2021-09-01 19:03 UTC, bryanpizzillo commented on src/services/api/clinical-trials-search-api/__tests__/getClinicalTrials.test.js
> +		const badClient = axios.create({
This does not seem to have a scope defined for nock. do it may be connecting to the internet.

2021-09-01 19:04 UTC, bryanpizzillo commented on src/services/api/clinical-trials-search-api/__tests__/getClinicalTrials.test.js
> +import { getClinicalTrials } from '../getClinicalTrials';
All tests should have a nock scope, and the test `scope.isDone();`

2021-09-01 19:11 UTC, bryanpizzillo commented on src/services/api/clinical-trials-search-api/getClinicalTrials.js
> +/**
There are now tests

2021-09-01 19:13 UTC, bryanpizzillo commented on src/services/api/clinical-trials-search-api/getClinicalTrials.js
> +			if (res.data.trials.length === 0 && res.data.total !== 0) {
Can we also check if `(res.data.total === 0 && res.data.trials.length !== 0)

2021-09-02 19:30 UTC, bryanpizzillo requested changes
I will do these real quick

2021-09-02 19:30 UTC, bryanpizzillo commented on src/views/Manual/Manual.jsx
>  			{/* ::: Intro Text ::: */}
This code is crazy, @arcepaul and I discussed it and we really should not have so many things "rendering" above and below the spinner if they do not show during load.

2021-09-02 19:30 UTC, bryanpizzillo commented on src/views/Intervention/Intervention.jsx
> +				{fetchedAndHasTrials(fetchState) && (
This code is crazy, @arcepaul and I discussed it and we really should not have so many things "rendering" above and below the spinner if they do not show during load.

2021-09-02 19:30 UTC, bryanpizzillo commented on src/views/Disease/Disease.jsx
> +			{replacedText.introText.length > 0 && fetchedAndHasTrials(fetchState) && (
This code is crazy, @arcepaul and I discussed it and we really should not have so many things "rendering" above and below the spinner if they do not show during load.

2021-09-02 19:47 UTC, seyilonge-nci commented
> I will do these real quick

👍

2021-09-02 20:34 UTC, bryanpizzillo approved these changes
This is good for me now.

2021-09-07 23:16 UTC, alinai commented
Verified the request and response for DLPs and MLPs and no trial found pages on React and verified that the results are displayed as expected.
Noticed that MLP headers are different between react and Prod but the MLP headers on react are same as react develop which I guess is a content issue.
cc: @KateMashkinaNIH

2021-09-07 23:27 UTC, kate-mashkina approved these changes

2021-09-07 23:32 UTC, merged