(#141) Redirect NoTrials from a non-existent page fix
NCIOCPL/clinical-trials-listing-app pull request #144
Opened 2022-01-13 04:56 UTC by alerosad

- Disease redirects to NoTrials now
- Intervention redirects to NoTrials now
- Manual redirects to NoTrials now
- having issue with integration test

2022-01-14 04:48 UTC, alerosad commented
Valid page number:

https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-144/breast-cancer?cfg=0

Invalid page number:

https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-144/breast-cancer?cfg=0&pn=900

2022-01-18 15:22 UTC, kate-mashkina commented
@alinai

2022-01-18 15:24 UTC, kate-mashkina requested changes

2022-01-18 15:24 UTC, kate-mashkina commented on src/views/Disease/Disease.jsx
> +		console.log('huh');
remove this logging

2022-01-18 15:24 UTC, kate-mashkina commented on src/views/Disease/Disease.jsx
> +			console.log('major yuh');
and this

2022-01-18 15:24 UTC, kate-mashkina commented on src/views/Disease/Disease.jsx
> +			console.log('got here i guess');
loving your logs, but they got to go :)

2022-01-18 15:24 UTC, kate-mashkina commented on src/views/Disease/Disease.jsx
> +			console.log('in second statement');
here as well

2022-07-14 18:06 UTC, KateMashkinaNIH approved these changes

2022-07-14 18:08 UTC, KateMashkinaNIH commented
tested on ode450 for disease, intervention and 1 manual page

2022-07-14 18:14 UTC, merged