(#149) getClinicalTrials request should not contain a hardcoded version
NCIOCPL/clinical-trials-listing-app pull request #150
Opened 2022-07-12 20:20 UTC by alerosad

- updated src/index.js
- updated index.html
- updated clincal-trials-search-api/getClinicalTrials.js
- updated unit and integration tests accordingly
Closes #149

2022-07-12 23:43 UTC, KateMashkinaNIH requested changes

2022-07-12 23:43 UTC, KateMashkinaNIH commented on public/index.html
> +					ctsApiEndpoint: 'https://clinicaltrialsapi.cancer.gov/v2',
missing `/api `part here

2022-07-13 10:47 UTC, seyilonge-nci commented on public/index.html
> +					ctsApiEndpoint: 'https://clinicaltrialsapi.cancer.gov/v2',
👍

2022-07-13 21:46 UTC, arcepaul approved these changes

2022-07-13 21:46 UTC, merged