(#165) Update to Node 16 and npm 8
NCIOCPL/clinical-trials-listing-app pull request #166
Opened 2022-10-26 14:56 UTC by adriancofie

Closes #165

2022-10-27 04:22 UTC, seyilonge-nci requested changes

2022-10-27 04:22 UTC, seyilonge-nci commented on .nvmrc
> +16
Can you change this to `lts/gallium`

2022-11-02 14:32 UTC, seyilonge-nci approved these changes

2022-11-02 19:57 UTC, arcepaul approved these changes

2022-11-02 19:57 UTC, merged