(#29) Bug Fix Link to Trial should use NCI ID
NCIOCPL/clinical-trials-listing-app pull request #32
Opened 2021-02-25 22:50 UTC by alerosad

(#29) Bug Fix Link to Trial should use NCI ID

Closes #29

*Updated Manual.jsx, results-list.item.jsx, and results-list.jsx
*Updates to these files changed the manner in which NCI ID is retrieved
*Updated Index.html so that replaceToken is used
*Replace Token was used in order to parse the prettyURL dynamically
*Unit tests and Integration tests were updated accordingly

2021-02-25 22:52 UTC, alerosad commented
@VictoriaSunNIH @mworrest @blilianyu 
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-32?cfg=2

2021-02-26 20:27 UTC, mworrest commented
I am seeing the NCI ID in the URL however the links don't go to a page but maybe that is expected at this stage.

2021-03-01 16:39 UTC, VictoriaSunNIH commented
@alerosad , @seyilonge-nci  - I see the same as michelle now, the ID in the URL is correct but is appneded to react-app-dev. Is it supposed to be that way?

2021-03-01 20:10 UTC, alerosad commented
I'll make sure to fix that

2021-03-01 20:57 UTC, seyilonge-nci requested changes

2021-03-01 21:01 UTC, seyilonge-nci commented
> @alerosad , @seyilonge-nci - I see the same as michelle now, the ID in the URL is correct but is appneded to react-app-dev. Is it supposed to be that way?

As @alerosad mentioned above. The fix actually includes using the relative link which is what's supplied to initialize the app. As you noted the page doesn't exist on react-app-dev. This is the way :-).

2021-03-02 03:18 UTC, alerosad commented on src/components/molecules/results-list/results-list-item/results-list-item.jsx
> +const context = {nci_id: nciId};
I did not

2021-03-02 03:53 UTC, alerosad reviewed
Ok, went ahead and made those changes you asked for. Thanks!

2021-03-02 12:53 UTC, seyilonge-nci requested changes

2021-03-02 12:53 UTC, seyilonge-nci commented on public/index.html
> +						'https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?id={{nci_id}}',
This contains the absolute link. Not using relative as above.

2021-03-02 12:53 UTC, seyilonge-nci commented on public/index.html
> +						'https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?=id{{nci_id}}',
Same as above.

2021-03-02 12:53 UTC, seyilonge-nci commented on public/index.html
> +						'https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?=id{{nci_id}}',
Same as above.

2021-03-02 12:53 UTC, seyilonge-nci commented on src/components/molecules/results-list/results-list-item/__tests__/results-list-item.test.js
> +		//const resultsItemTitleLink = '/about-cancer/treatment/clinical-trials/search/v?id={{nci_id}}';
Can you remove this since it's not used.

2021-03-02 12:53 UTC, seyilonge-nci commented on src/views/ErrorBoundary/PageNotFound.jsx
> +					<form onSubmit={{executeSearch}} type="text">
Why did you update this file?

2021-03-02 12:53 UTC, seyilonge-nci commented on src/components/molecules/results-list/__tests__/results-list.tests.js
> +		/*
Since this is not used here, and commented out. Please remove from file.

2021-03-02 14:23 UTC, alerosad commented
Ok, went ahead and made those changes

2021-03-02 14:40 UTC, VictoriaSunNIH commented
Since @seyilonge-nci says this is the way, the PR passes for us! :)

2021-03-03 18:52 UTC, alerosad commented
Ok, went back and made those changes to the bottom left url, and it still uses the relative path. Should be good to go now

2021-03-03 18:57 UTC, VictoriaSunNIH commented
Looks good, thanks @alerosad ! :)

2021-03-03 18:58 UTC, sarinapadilla commented
@alerosad I am still seeing detailedViewPagePrettyUrlFormatter as the Clinical Trials Search view page URL rather than /clinical-trials/{{nci_id}}. Please update this!

2021-03-03 19:27 UTC, alerosad commented
> @alerosad I am still seeing detailedViewPagePrettyUrlFormatter as the Clinical Trials Search view page URL rather than /clinical-trials/{{nci_id}}. Please update this!

My understanding of how cancer.gov redirects based on the given prettyURL was wrong, I'll go ahead and change it. I think I understand now how to approach it, thanks!

2021-03-03 21:21 UTC, alerosad commented
Ok, it should now be good to go.

2021-03-04 00:27 UTC, seyilonge-nci requested changes

2021-03-04 00:27 UTC, seyilonge-nci commented on src/components/molecules/results-list/results-list-item/results-list-item.jsx
> +	const hoverURL = 'clinicaltrials/'+ nciId;
`hoverURL` should no longer be needed.

2021-03-04 00:27 UTC, seyilonge-nci commented on src/components/molecules/results-list/results-list-item/results-list-item.jsx
> +	function handleClick(e) {
What's this function for?

2021-03-04 00:27 UTC, seyilonge-nci commented on src/views/ErrorBoundary/PageNotFound.jsx
> +					<form onSubmit={{executeSearch}} >
The only change in this file is the extra space. Getting rid of the space should exclude this file from your PR.

2021-03-04 16:32 UTC, seyilonge-nci approved these changes

2021-03-04 18:00 UTC, KateMashkinaNIH requested changes

2021-03-04 18:00 UTC, KateMashkinaNIH commented on src/components/molecules/results-list/results-list-item/__tests__/results-list-item.test.js
> +		const resultsItemTitleLink = 'http://sample.com/test-url/v?id={{nci_id}}';
This should probably be changed to /clinicaltrials/{{nci_id}}

2021-03-04 18:00 UTC, KateMashkinaNIH commented on src/components/molecules/results-list/results-list-item/__tests__/results-list-item.test.js
> +		const resultsItemTitleLink = 'http://sample.com/test-url/v?id={{nci_id}}';
then expect the following 
expect(container.querySelector('a')).toHaveAttribute(
			'href',
			'/clinicaltrials/NCI-12984'
		);

2021-03-04 19:56 UTC, kate-mashkina approved these changes

2021-03-04 19:57 UTC, KateMashkinaNIH approved these changes

2021-03-11 15:20 UTC, arcepaul approved these changes

2021-03-11 15:20 UTC, merged