(#12) Page Not Found for Disease
NCIOCPL/clinical-trials-listing-app pull request #40
Opened 2021-03-18 17:59 UTC by kate-mashkina

- enabled PageNotFound for 404 status
- added prerender meta tag
- added integration tests

Closes #12

2021-03-18 18:11 UTC, kate-mashkina commented
@VictoriaSunNIH @mworrest  @alinai here are links for review : https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-40/c456667?cfg=0 and https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-40/chicken-nugget?cfg=0

2021-03-23 19:22 UTC, kate-mashkina commented
@mworrest as we discussed, search bar and submit button are now full width at <641 px - please re-check the PR https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-40/c456667?cfg=0

2021-03-23 19:42 UTC, mworrest commented
Looks good--thanks!

2021-03-23 22:46 UTC, alinai commented
Looks good. Thanks @kate-mashkina!

2021-03-24 16:09 UTC, bryanpizzillo requested changes
Please fix the proxy to support known 404 urls that should respond with a 404, and not litter the test output with file not found errors.

The example from the output:
```
[Error: ENOENT: no such file or directory, open '/home/runner/work/clinical-trials-listing-app/clinical-trials-listing-app/support/mock-data/listing-information/c123455.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/clinical-trials-listing-app/clinical-trials-listing-app/support/mock-data/listing-information/c123455.json'
}
No listing-information mock found for request.
    ✓ Page Load Analytics fires for a 404 on a disease dynamic listing page with non-existent c-code (2292ms)
[Error: ENOENT: no such file or directory, open '/home/runner/work/clinical-trials-listing-app/clinical-trials-listing-app/support/mock-data/listing-information/chicken-nugget.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/clinical-trials-listing-app/clinical-trials-listing-app/support/mock-data/listing-information/chicken-nugget.json'
}
```

Additionally I see another error in the logs:
(node:3270) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

2021-03-24 19:49 UTC, kate-mashkina commented
@bryanpizzillo I took care of the proxy. 
The other error mentioned appears to be an obvious Cypress's issue and still outstanding (see here https://github.com/cypress-io/cypress/issues/1305) - but the good thing is that Cypress assures it does not cause things to crash.
I've done more digging and the same issue was also present in drug dictionary tests( precisely at the 10th feature it would be logged... so it just happens that pageNotFound is the 10th)

2021-03-29 13:25 UTC, seyilonge-nci approved these changes

2021-04-01 14:23 UTC, sarinapadilla approved these changes

2021-04-01 17:21 UTC, arcepaul commented on support/mock-data/listing-information/c123455-404.json
> +{"Message":"Could not find codes 'c12345'."}
blecch.  So this came up in the app scan as having needed to be changed.  @sarinapadilla those changes haven't been made yet, right?

2021-04-01 20:04 UTC, bryanpizzillo approved these changes

2021-04-01 20:07 UTC, arcepaul approved these changes

2021-04-01 20:07 UTC, merged