(#52) Fix No Trials Found functionality
NCIOCPL/clinical-trials-listing-app pull request #54
Opened 2021-04-07 15:05 UTC by sarinapadilla

* Update CTLViewsHoC with logic to handle /notrials route and prerender status
* Update unit tests for CTLViewsHoC /notrials cases
* Update NoTrialsFound to display prerender status
* Update integration tests for NoTrialsFound, Disease, and PageNotFound

2021-04-07 16:51 UTC, sarinapadilla commented
@VictoriaSunNIH @mworrest @alinai this is ready for testing. Here's a few example URLs for different scenarios.

1) Redirects to /notrials?p1={pretty-url-name}, shows No Trials Page with 302 prerender status
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/C3037?cfg=0
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/chronic-fatigue-syndrome?cfg=0

2) Redirect to /notrials?p1={pretty-url-name}, shows No Trials Page with 404 prerender status
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/notrials?p1=C3037&cfg=0

3) Shows No Trials Page with 404 prerender status
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/notrials?p1=chronic-fatigue-syndrome&cfg=0

4) Displays Page Not Found with 404 prerender status
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/notrials?p1=chicken&cfg=0
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/notrials?p1=C123456789&cfg=0

If you guys need more examples for diseases that return no trials (with one code, multiple codes, etc) I can find them for you!

2021-04-07 18:32 UTC, mworrest commented
I can't speak for the prerender status but the redirects look accurate.

2021-04-08 13:34 UTC, alinai commented
Looks good to me. Thanks @sarinapadilla!

2021-04-12 18:43 UTC, sarinapadilla commented
@VictoriaSunNIH @mworrest @alinai @KateMashkinaNIH , this is ready for testing again! We have changed some requirements so I've updated the scenarios.

Redirects to /notrials?p1={code}, shows No Trials Page with 301 prerender status and prerender-header
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/C3037?cfg=0

Redirects to /notrials?p1={pretty-url-name}, shows No Trials Page with 302 prerender status and prerender-header
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/chronic-fatigue-syndrome?cfg=0

Shows No Trials Page with 404 prerender status and no prerender-header
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/notrials?p1=C3037&cfg=0
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/notrials?p1=chronic-fatigue-syndrome&cfg=0

Displays Page Not Found with 404 prerender status and no prerender-header
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/notrials?p1=chicken&cfg=0
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-54/notrials?p1=C123456789&cfg=0

2021-04-12 18:46 UTC, sarinapadilla commented
Additionally, @KateMashkinaNIH, please test that the prerender meta tags are being populated correctly for ugly to pretty URL name redirects (#22), which is also part of this PR.

2021-04-12 20:01 UTC, KateMashkinaNIH requested changes

2021-04-12 20:06 UTC, KateMashkinaNIH commented
tested various redirects - meta tags looks good

2021-04-12 20:13 UTC, alinai commented
Looks good to me. Some examples of diseases with multiple C-codes provided by @sarinapadilla ,
C-Code = ["C43625", "C114993"], pretty url = "pleomorphic-hepatocellular-cancer"
C-Code = ["C4661", "C115253"], pretty url = "primary-melanocytic-lesion-of-meninges"

Thanks @sarinapadilla!

2021-04-12 20:15 UTC, VictoriaSunNIH commented
Looks good to me too - so it sounds like this passes both QA and UX review - I'm updating labels.

2021-04-12 20:20 UTC, sarinapadilla commented on cypress/integration/PageNotFound/NoTrialsRoutePageNotFound.feature
> +
We don't want the noindex tag on the Page Not Found, but you're right that we should be checking for the prerender status code tag! It's been fixed

2021-04-13 14:04 UTC, KateMashkinaNIH approved these changes

2021-04-15 15:53 UTC, arcepaul approved these changes

2021-04-15 16:07 UTC, merged